### PR TITLE
Issues fixes

### LINKED ISSUE #500: Course Assistant should be able to remove students
If you are the Course Instructor, in the "instructor view", you can see the "three dots" icon at the left-most side where instructor can remove students:
image

**Please implement the same instructor view for Course Assistant**

### PR DESCRIPTION
**Pull request by Brainenjii**
fix #500

### CODE REVIEW

File: src/containers/Cohort/Cohort.js [hunk 1]
```diff
@@ -108,10 +108,6 @@ class Cohort extends React.PureComponent {
   render() {
     const { dispatch, classes, cohort, courses, currentUser, ui } = this.props;
 
-    if (!(currentUser && currentUser.uid)) {
```
Comment (FeynmanDNA) [inline src/containers/Cohort/Cohort.js]: @Brainenjii we will hide the individual cohort page from unregistered user. Can I add this back in the next PR?
